# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('fps', models.IntegerField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('min_x', models.IntegerField()),
                ('min_y', models.IntegerField()),
                ('max_x', models.IntegerField()),
                ('max_y', models.IntegerField()),
                ('occupied', models.BooleanField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Camera')),
            ],
        ),
    ]
