# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160625_1754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rect',
            new_name='Roi',
        ),
    ]
